trigger: 
- master
pool:
 name: 'local'
 demands: 
 - Agent.Name -equals amazonliux
stages:
  - stage: Build
    jobs:
    - job:
      displayName: 'Maven Build'
      steps:
      - script: 
         echo "Hello"
          
       