trigger: 
- master
pool:
 name: 'local'
 demands: 
 - Agent.Name -equals amazonliux
stages:
  - stage: Build
    pool:
     name: 'local'
     demands: 
       - Agent.Name -equals amazonliux
    jobs:
    - job:
      displayName: 'Maven Build'
      steps:
      - task: Maven@4
        inputs:
          mavenPomFile: 'pom.xml'
          goals: 'clean package'
          publishJUnitResults: false
          codeCoverageToolOption: 'JaCoCo'
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
              
          
       